# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: numbers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'numbers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnumbers.proto\x12\x07numbers\"\x1c\n\rNumberRequest\x12\x0b\n\x03max\x18\x01 \x01(\x05\" \n\x0eNumberResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32Y\n\x0fNumberGenerator\x12\x46\n\x0fGenerateNumbers\x12\x16.numbers.NumberRequest\x1a\x17.numbers.NumberResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numbers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERREQUEST']._serialized_start=26
  _globals['_NUMBERREQUEST']._serialized_end=54
  _globals['_NUMBERRESPONSE']._serialized_start=56
  _globals['_NUMBERRESPONSE']._serialized_end=88
  _globals['_NUMBERGENERATOR']._serialized_start=90
  _globals['_NUMBERGENERATOR']._serialized_end=179
# @@protoc_insertion_point(module_scope)
